import { StyleSheet } from 'react-native';
import { rose_theme } from '@constants/rose_theme';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: rose_theme.rose_dark,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: rose_theme.rose_lightest,
    textAlign: 'center',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: rose_theme.subtitle,
    textAlign: 'center',
    marginBottom: 40,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: rose_theme.light_bg_secondary,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: rose_theme.dark_border,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: rose_theme.dark_input_bg,
    color: rose_theme.white,
  },
  inputFocused: {
    borderColor: rose_theme.rose_light,
    backgroundColor: rose_theme.dark_surface,
  },
  passwordContainer: {
    position: 'relative',
  },
  passwordToggle: {
    position: 'absolute',
    right: 12,
    top: 12,
    padding: 4,
  },
  passwordToggleText: {
    color: rose_theme.rose_lightest,
    fontSize: 14,
    fontWeight: '600',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: rose_theme.dark_border,
    borderRadius: 4,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: rose_theme.rose_light,
    borderColor: rose_theme.rose_light,
  },
  checkboxIcon: {
    color: rose_theme.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontSize: 14,
    color: rose_theme.subtitle,
    flex: 1,
  },
  loginButton: {
    backgroundColor: rose_theme.rose_main,
    borderRadius: 8,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 20,
  },
  loginButtonDisabled: {
    backgroundColor: rose_theme.dark_border,
  },
  loginButtonText: {
    color: rose_theme.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statusButton: {
    backgroundColor: rose_theme.rose_dark,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 20,
  },
  statusButtonText: {
    color: rose_theme.white,
    fontSize: 14,
    fontWeight: '600',
  },
  statusMessage: {
    textAlign: 'center',
    fontSize: 14,
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  statusSuccess: {
    color: rose_theme.success,
  },
  statusError: {
    color: '#f44336',
  },
  errorText: {
    color: '#f44336',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    backgroundColor: rose_theme.dark_surface,
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: rose_theme.light_bg_secondary,
  },
  configButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: rose_theme.dark_border,
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  configButtonText: {
    color: rose_theme.light_bg_secondary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: rose_theme.dark_input_bg,
    borderRadius: 12,
    padding: 20,
    margin: 20,
    width: '80%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: rose_theme.light_bg_secondary,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 8,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: rose_theme.dark_border,
  },
  modalButtonSave: {
    backgroundColor: rose_theme.rose_main,
  },
  modalButtonText: {
    color: rose_theme.white,
    fontSize: 14,
    fontWeight: '600',
  },
});
