import { StyleSheet } from 'react-native';
import { rose_theme } from '@constants/rose_theme';

export const personListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: rose_theme.rose_dark,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    paddingTop: 40,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: rose_theme.white,
    flex: 1,
    textAlign: 'center',
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    padding: 8,
    position: 'relative',
  },
  filterIndicator: {
    position: 'absolute',
    top: 4,
    right: 4,
  },
  filterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: rose_theme.rose_lightest,
  },
  refreshButton: {
    padding: 8,
  },
  floatingButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: rose_theme.rose_lightest,
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: rose_theme.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: rose_theme.rose_light,
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    minWidth: 70,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: rose_theme.white,
  },
  statLabel: {
    fontSize: 12,
    color: rose_theme.white,
    marginTop: 4,
  },
  listContainer: {
    padding: 20,
    paddingTop: 0,
  },
  card: {
    backgroundColor: rose_theme.white,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: rose_theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  personName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: rose_theme.light_text_primary,
    marginBottom: 8,
  },
  personId: {
    fontSize: 14,
    color: rose_theme.light_text_secondary,
    fontWeight: '600',
  },
  badgeContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  typeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  stateBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: rose_theme.white,
  },
  cardContent: {
    gap: 12,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: rose_theme.light_text_primary,
    minWidth: 80,
  },
  infoValue: {
    fontSize: 14,
    color: rose_theme.light_text_secondary,
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: rose_theme.white,
    marginTop: 16,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: rose_theme.disabled_text,
    marginTop: 16,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: rose_theme.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: rose_theme.light_border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: rose_theme.light_text_primary,
  },
  closeButton: {
    padding: 5,
  },
  filterSection: {
    marginBottom: 25,
  },
  filterLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: rose_theme.light_text_primary,
    marginBottom: 10,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: rose_theme.light_bg_secondary,
    borderRadius: 10,
    paddingHorizontal: 15,
    height: 50,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: rose_theme.light_text_primary,
  },
  clearSearchButton: {
    padding: 5,
  },
  sortOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  sortButton: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: rose_theme.light_disabled,
    borderWidth: 1,
    borderColor: rose_theme.light_border,
  },
  sortButtonActive: {
    backgroundColor: rose_theme.rose_main,
    borderColor: rose_theme.rose_main,
  },
  sortButtonText: {
    fontSize: 14,
    color: rose_theme.light_text_secondary,
    fontWeight: '500',
  },
  sortButtonTextActive: {
    color: rose_theme.white,
    fontWeight: 'bold',
  },
  roleOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roleButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 15,
    backgroundColor: rose_theme.light_disabled,
    borderWidth: 1,
    borderColor: rose_theme.light_border,
    marginBottom: 8,
  },
  roleButtonActive: {
    backgroundColor: rose_theme.rose_main,
    borderColor: rose_theme.rose_main,
  },
  roleButtonText: {
    fontSize: 12,
    color: rose_theme.light_text_secondary,
    fontWeight: '500',
  },
  roleButtonTextActive: {
    color: rose_theme.white,
    fontWeight: 'bold',
  },
  filterActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 15,
  },
  clearButton: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 10,
    backgroundColor: rose_theme.light_bg_secondary,
    alignItems: 'center',
  },
  clearButtonText: {
    fontSize: 16,
    color: rose_theme.light_text_secondary,
    fontWeight: '600',
  },
  applyButton: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 10,
    backgroundColor: rose_theme.rose_main,
    alignItems: 'center',
  },
  applyButtonText: {
    fontSize: 16,
    color: rose_theme.white,
    fontWeight: 'bold',
  },
  // Edit modal styles
  modalKeyboardAvoidingView: {
    flex: 1,
  },
  editModalContent: {
    backgroundColor: rose_theme.dark_surface,
    borderRadius: 12,
    margin: 20,
    maxHeight: '90%',
    borderWidth: 2,
    borderColor: rose_theme.rose_main,
  },
  editFormContainer: {
    padding: 20,
    paddingBottom: 20,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputGroupLast: {
    marginBottom: 30,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: rose_theme.text_light,
    marginBottom: 8,
  },
  input: {
    backgroundColor: rose_theme.dark_bg,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: rose_theme.text_light,
    borderWidth: 1,
    borderColor: rose_theme.rose_main,
  },
  inputDisabled: {
    backgroundColor: rose_theme.dark_input_bg,
    opacity: 0.7,
  },
  dateInput: {
    backgroundColor: rose_theme.dark_bg,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    borderWidth: 1,
    borderColor: rose_theme.rose_main,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateInputText: {
    color: rose_theme.text_light,
    fontSize: 14,
    flex: 1,
  },
  pickerContainer: {
    backgroundColor: rose_theme.dark_bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: rose_theme.rose_main,
    overflow: 'hidden',
  },
  picker: {
    color: rose_theme.text_light,
  },
  stateButtonsContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  stateButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: rose_theme.dark_surface,
    borderWidth: 1,
    borderColor: rose_theme.rose_main,
    alignItems: 'center',
  },
  stateButtonActive: {
    backgroundColor: rose_theme.rose_main,
    borderColor: rose_theme.rose_main,
  },
  stateButtonText: {
    fontSize: 14,
    color: rose_theme.text_light,
    fontWeight: '500',
  },
  stateButtonTextActive: {
    fontWeight: '600',
    color: rose_theme.white,
  },
  passwordSection: {
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: rose_theme.rose_main,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: rose_theme.text_light,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: rose_theme.dark_subtitle,
    marginBottom: 16,
  },
  saveButton: {
    backgroundColor: rose_theme.success_green,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    gap: 8,
    margin: 20,
  },
  saveButtonText: {
    fontSize: 16,
    color: rose_theme.white,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  // Edit Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: rose_theme.rose_dark,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: rose_theme.rose_main,
  },
  editModalHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: rose_theme.white,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardAvoidingView: {
    flex: 1,
    flexDirection: 'column',
  },
  editFormScrollView: {
    flex: 1,
    padding: 20,
  },
});
